# Generated by Django 3.2.5 on 2021-12-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='seat_number',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('3', '3'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat_row',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='hall_no',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('D', 'Diamond'), ('P', 'Platinum'), ('G', 'Gold'), ('S', 'Silver'), ('B', 'Bronze')], default='D', max_length=1),
        ),
    ]
